### ISSUE TITLE
java 客户端采用kona-ssl连接异常

### ISSUE THREAD

**Issue by ckz119** [Tongsuo-Project/Tongsuo#657]
你好，java客户端采用kona-ssl连接报错，异常如下：
Caused by: com.tencent.kona.sun.security.validator.ValidatorException: PKIX path building failed: com.tencent.kona.sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at com.tencent.kona.sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:391)
	at com.tencent.kona.sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:245)
	at com.tencent.kona.sun.security.validator.Validator.validate(Validator.java:256)
	at com.tencent.kona.sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:232)
	at com.tencent.kona.sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:133)
	at com.tencent.kona.sun.security.ssl.TLCPCertificate$TLCPCertificateConsumer.checkServerCerts(TLCPCertificate.java:736)
	... 15 more
证书是用仓库里的 https://github.com/Tongsuo-Project/Tongsuo/blob/master/test/certs/sm2/chain-ca.crt这个ca证书，请问是我证书错了还是客户端问题

**Comment by johnshajiang** [comment]
对于你在TencentKonaSMSuite中提出的相关问题，已有回复。
https://github.com/Tencent/TencentKonaSMSuite/issues/876
